argo-cd:
  installCRDs: false
  global:
    image:
    # argo version
      tag: v2.2.5
  dex:
    enabled: false
  server:
    extraArgs:
    # without TLS support
      - --insecure
    config:
      repositories: |
        - type: helm
          name: stable
          url: https://charts.helm.sh/stable
        - type: helm
          name: argo-cd
          url: https://argoproj.github.io/argo-helm